### ISSUE TITLE
doesn't work with linux ( 32bit KSP on 64bit OS )

### ISSUE THREAD

**Issue by phreaker0** [unixunion/PsimaxSerial#3]
i tried your released binaries (KSPSerialIO-0.17.1.zip) with linux (Ubuntu 14.04 LTS) and KSP 1.0. But it doesn't work. My config:

```
﻿<?xml version="1.0" encoding="utf-8"?>
<config>
    <string name="DefaultPort">/dev/ttyUSB0</string>
    <int name="BaudRate">38400</int>
    <int name="HandshakeDelay">2000</int>
    <double name="refresh">0.25</double>
    <bool name="NoDetect">0</bool>
</config>
```

First time i got the following debug message:

```
Error opening serial port /dev/ttyUSB0: libMonoPosixHelper.so
```

The second time i tried (with NoDetect set to 1) there was an exception:

```
[Exception]: DllNotFoundException: libMonoPosixHelper.so
```

I then downgraded to KSP 0.90 beta, but the same exception was raised.

Other serial applications (like cutecom) work.

**Comment by unixunion** [comment]
Hi!

Interresing, can you locate libMonoPosixHelper.so somewhere on ur machine?

Are you running the steam version or the standalone?

I'll see if I can spin up a virtualbox version and try it.

Do you know if 0.90 mods need to be rebuild for 1.0?

/K

On Friday, May 1, 2015, phreaker0 notifications@github.com wrote:

> i tried your released binaries (KSPSerialIO-0.17.1.zip) with linux (Ubuntu
> 14.04 LTS) and KSP 1.0. But it doesn't work. My config:
> 
> ﻿<?xml version="1.0" encoding="utf-8"?>
> <config>
>     <string name="DefaultPort">/dev/ttyUSB0</string>
>     <int name="BaudRate">38400</int>
>     <int name="HandshakeDelay">2000</int>
>     <double name="refresh">0.25</double>
>     <bool name="NoDetect">0</bool>
> </config>
> 
> First time i got the following debug message:
> 
> Error opening serial port /dev/ttyUSB0: libMonoPosixHelper.so
> 
> The second time i tried (with NoDetect set to 1) there was an exception:
> 
> [Exception]: DllNotFoundException: libMonoPosixHelper.so
> 
> I then downgraded to KSP 0.90 beta, but the same exception was raised.
> 
> Other serial applications (like cutecom) work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/unixunion/PsimaxSerial/issues/3.

##

**Comment by phreaker0** [comment]
Yeah the library is located here on my system (64 bit btw):

 /usr/lib/libMonoPosixHelper.so

I tried to just copy it into the GameData/KSPSerialIO/ folder, but the exception was still there.

I installed KSP 1.0 now onto a windows machine I had lying around, and there it works. It says that a display is found.

**Comment by phardy** [comment]
I just encountered the same problem attempting to run the 32 bit KSP binary on my 64 bit Debian install.

It's happening because /usr/lib/libMonoPosixHelper.so is a 64 bit library. When you run the 32 bit KSP, it tries to link in appropriate 32 bit libraries, and there's no 32 bit libMonoPosixHelper available.

The only really viable solution I can see for this is to run the 64 bit KSP binary. On my system, this is all that's required, the correct libMonoPosixHelper lib is found and linked in, and the serial port is opened.

In theory it should also be possible to install a 32 bit mono environment with a command like

```
sudo apt-get install mono-complete:i386
```

But on Debian testing it looks like the 32 bit and 64 bit mono packages clash, and only one set can be installed at a time. I'm almost certain that removing the 64 bit and installing the 32 bit on Ubuntu will break a lot of other packages that depend on mono.

**Comment by unixunion** [comment]
So looks like I need to mention this in the project. I don't know if I can support crossing 64 and 32 bit setups.

**Comment by unixunion** [comment]
I will close this issue with the resolution being to run 64bit KSP on 64bit OS's.
